version: '2'
services:
  db:
    image: postgres:13
    ports:
      - "10007:5432"
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
    restart: always
    volumes:
        - ./postgresql:/var/lib/postgresql/data

  web:
    # image: odoo:14
    image: koperasi:VERSION
    build : .

    depends_on:
      - db
    ports:
      - "20007:8069"
    tty: true
    command: -- --dev=reload
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - ./addons/koperasi-odoo-14:/mnt/extra-addons
      - ./etc:/etc/odoo
    restart: always